unstable_features = true
condense_wildcard_suffixes = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
hex_literal_case = "Lower"
imports_granularity = "Module"
max_width = 80
merge_derives = false
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
tab_spaces = 2
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
